Db interface rework
genouest/genouestaccountmanager pull request #384
Opened 2022-12-06 14:54 UTC by KonoganB

First version of a new database management workflow, following the following issue: https://github.com/genouest/genouestaccountmanager/issues/370 

Feel free to suggest any changes. 

User can now ask for a database by giving more info, and the admins can visualize pending requests and validate them as they see fit.

2022-12-06 15:52 UTC, osallou requested changes

2022-12-06 15:52 UTC, osallou commented on manager2/src/app/database/database.component.html
> +            <button type="button" class="btn btn-primary" (click)="db_ask()" data-dismiss="modal">Create Database</button>
plutot "request database"

2022-12-06 15:52 UTC, osallou commented on manager2/src/app/database/database.component.html
> +            <button type="button" class="btn btn-primary" (click)="db_ask()" data-dismiss="modal">Create Database</button>
request MySQL database d'ailleurs...

2022-12-06 15:52 UTC, osallou commented on routes/database.js
>              await dbsrv.mongo_events().insertOne({'owner': session_user.uid, 'date': new Date().getTime(), 'action': 'database ' + req.params.id + ' created by ' +  session_user.uid, 'logs': []});
du coup ici on dit qu'elle a été créé par celuiqui l'a validé, faudrait plutot comme message  ... created for ' + db.owner

2022-12-06 15:52 UTC, osallou commented on tests/docker-compose.yml
> +            - gomngr_auth=fake
on ne change pas le compose de test.....

2022-12-07 15:58 UTC, osallou requested changes
lors de la demande de creation de db, aucun mail n'est envoyé (pour la demande de projet c'est le cas). Du coup on n'est pas au courant de la demande

dans la page utilisateur, il y a le panel database, il y a tjs la possibilité de créer une db directement via ce panel (input + bouton create)

2022-12-07 15:58 UTC, osallou commented on routes/database.js
> +        await dbsrv.mongo_events().insertOne({'owner': session_user.uid, 'date': new Date().getTime(), 'action': 'database request' + req.params.id + ' deleted by ' +  session_user.uid, 'logs': []});
manque un espace après request

2022-12-07 15:58 UTC, osallou commented on routes/database.js
> +        await dbsrv.mongo_events().insertOne({'owner': session_user.uid,'date': new Date().getTime(), 'action': 'database request' + req.params.id+ ' deleted by ' +  session_user.uid, 'logs': []});
manque un espace après request

2022-12-07 16:04 UTC, osallou commented
commentaire supplémentaire:

côté backend ds router.post('/database/:id' ...)

avant , admin et utilisateur pouvaient créer une db

maintenant cela doit etre limité aux admins (puisque le user fait une request)

2022-12-07 16:07 UTC, osallou commented
les tests unitaires doivent après coup (une fois limité aux admin) échouer

le test devrait faire une request pour un user, et la valider par un admin

2022-12-07 16:31 UTC, KonoganB commented
Pour la page user, on en a discuté avec Matéo et nous ne sommes pas arrivés à une conclusion. Il faudrait que je laisse l'option pour les autres instances (afin de garder cela modulaire) mais cela voudrait dire que les 2 manières de créer une db coexisteraient dans le backend? Sinon effectivemment je préfère la faire sauter.

2022-12-07 16:42 UTC, KonoganB commented
Très bien je la retire et j'attache la clef existante à l'onglet

2023-01-18 17:13 UTC, KonoganB commented
Should be good to go, mails are sent and I updated the tests. Since the admin tests are triggered before the users' tests, can't make it sequential. So they are separate, each one running with its own database.

2023-01-23 09:55 UTC, osallou commented on .gitignore
> +tests/docker-compose.yml
pourquoi ignorer ces fichiers ?

2023-01-23 09:55 UTC, osallou commented on manager2/src/app/admin/databases/databases.component.html
> +                <th>Expected Expiration</th></tr>
expiration, pas expected expiration

2023-01-23 09:55 UTC, osallou commented on manager2/src/app/admin/databases/databases.component.ts
> +                err => { this.dbmsg_error = err.error.message; console.log('failed to delete database')}
failed to reject, pas to delete

2023-01-23 09:55 UTC, osallou commented on manager2/src/app/database/database.component.ts
> +    console.log(this.db)
virer les console.log

2023-01-23 10:47 UTC, KonoganB commented on .gitignore
> +tests/docker-compose.yml
J'utilisais les VM pour le backend, Donc je devais faire beaucoup de commits pour tester des choses en backend, et je voulais pas commit les tweaks de config nécessaires pour le dev. Je suis revenu avec le backend en local, donc plus besoin de ça.

2024-07-05 12:53 UTC, merged